services:
  redis:
    image: redis
    ports:
      - 6379:6379
  # web:
  #   build:
  #     context: .
  #   environment:
  #     FLASK_APP: run
  #     FLASK_DEBUG: 1
  #   volumes:
  #     - .:/app
  #   command: flask run -h 0.0.0.0
  #   ports:
  #     - 5000:5000
  #     - 8099:8099
  # celery:
  #   build:
  #       context: .
  #   volumes:
  #     - .:/app
  #   command: celery -A make_celery worker -c 1 --loglevel=info
  #   depends_on:
  #     - redis